functions/definitions/webhookHandler.js

added logging for non-200 returns

added logging for non-200 returns

---

functions/.prettierrc
functions/src/definitions/auxillary/analyticsUpdateSheet.js
functions/src/definitions/batchJobs.js
functions/src/definitions/calculateSimilarity.js
functions/src/definitions/checkerHandlers.js
functions/src/definitions/common/classifier.js
functions/src/definitions/common/constants.js
functions/src/definitions/common/cosineSimilarityUtils.js
functions/src/definitions/common/counters.js
functions/src/definitions/common/mediaUtils.js
functions/src/definitions/common/responseUtils.js
functions/src/definitions/common/sendFactCheckerMessages.js
functions/src/definitions/common/sendMessage.js
functions/src/definitions/common/sendTelegramMessage.js
functions/src/definitions/common/sendWhatsappMessage.js
functions/src/definitions/common/utils.js
functions/src/definitions/onInstanceCreate.js
functions/src/definitions/onMessageUpdate.js
functions/src/definitions/onVoteRequestUpdate.js
functions/src/definitions/userHandlers.js
functions/src/definitions/webhookHandler.js
functions/src/index.js

`npx prettier --write ./src` was run with these rules. This is a safe change.
```
trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
```

Add and apply prettier

---

.github/workflows/firebase-deploy.yml
functions/package.json

Updated deployment action to install firebase

[Hotfix] Deployment Github Action

---

documentation/dataSchema.md
functions/src/definitions/checkerHandlers.js
functions/src/definitions/onInstanceCreate.js

As per title, to capture proxy of "difficulty" of fact checking

added acceptedTimestamp to voteRequest

---

integration-tests/checkmate.postman_collection.json

From the current list of conversation sequences, covers
```
if new user:
trigger NEW_USER
if user selects "Yes, show me":
trigger ONBOARDING 
if user selects "No, I'm good":
trigger GET_STARTED
if message is <15 chars: IRRELEVANT_AUTO: 
```
and
```
if message is not in database:
user receives MESSAGE_NOT_YET_ASSESSED
trigger checker template NEW_MESSAGE_RECEIVED
```

Add more tests

---

documentation/dataSchema.md
functions/src/definitions/common/responseUtils.js
functions/src/definitions/userHandlers.js

Changes
- Added isReplyImmediate and isMatched fields to instance object for stats purposes

added isReplyImmediate and isMatched

---

functions/src/definitions/common/responseUtils.js
functions/src/definitions/common/responseUtilsTs.ts
functions/src/definitions/common/sendWhatsappMessage.ts
functions/src/definitions/common/utils.ts
functions/src/types.ts

responseUtils.js is a pretty large file, so I broke up and moved some of the functions to responseUtilsTs.ts and imported them to responseUtils.js so we can move stuff incrementally.
As some minor code changes need to be done when type checking is added, this is more manageable then changing the whole file at once.

update some responseUtils to ts

---

documentation/dataSchema.md
functions/src/definitions/calculateSimilarity.ts
functions/src/definitions/userHandlers.js

In response to issue #117 
Changes
- Added direct database check for text and caption hash so that exact matches will go through a separate flow

117 url and phone number exact matches no longer matching

---

documentation/dataSchema.md
functions/src/definitions/common/constants.ts
functions/src/definitions/userHandlers.js

Resolves #121
- Capture utm parameters when a new user joins, if they join with one of our links.

link user with utm

---

functions/src/definitions/common/classifier.test.ts
functions/src/definitions/common/classifier.ts
functions/src/definitions/common/constants.ts
functions/src/definitions/userHandlers.js
functions/src/definitions/webhookHandler.js
integration-tests/checkmate.postman_collection.json
integration-tests/env.json

Fixes to address issues #144, #140, #139, #138
- Changed function timeout to 120 seconds
- Changed autoclassification as irrelevant to 8 seconds
- Changed machineCategory to not be assigned if isConvo is true for image messages
Also added boilerplate for handling whatsapp template message buttons in preparation for #141. This code won't be triggered for now as we don't yet blast whatsapp template messages to users.

Fixes for Issues 140 139 138

---

functions/src/definitions/common/responseUtils.ts
functions/src/definitions/common/sendMessage.ts
functions/src/definitions/common/utils.ts
functions/src/definitions/userHandlers.js

Resolves #146 
Summary
- For image handler, check that machineCategory is truthy in addition to existing checks when assigning isAssessed, isMachineCategorised etc.
- For text hander, check that machineCategory is truthy and not "error" in addition to existing checks when assigning isAssessed, isMachineCategorised etc.
- Fixed some erroneous TS imports

fixed issue #146

---

functions/src/definitions/checkerHandlers.js
functions/src/definitions/common/voteUtils.ts
functions/src/definitions/userHandlers.js

Fixes implement for #149 and #150
Summary:
- Force isAssessed to boolean
- Reset L2OthersSent and L2VotingMessageSent variables to null upon selection of info or its something else categories.

Fixes for #149 and #150

---

functions/src/definitions/common/machineLearningServer/operations.ts
functions/src/definitions/common/responseUtils.ts
functions/src/definitions/common/sendMessage.ts
functions/src/definitions/userHandlers.js

- Temporarily disables OCR in response to #152
- Refactored sendReferralMessage and added handling of the button from the WhatsApp message template.

Temporarily disable OCR

---

documentation/businessFlow.md
documentation/conversationFlow.md
documentation/conversationFlow.yml
documentation/dataSchema.md
documentation/detailedFlow.md

- Fixed `dataSchema.md` parsing error
- Wrapped contents in mermaid code block to allow for easy preview within VSCode through the mermaid plugin. https://marketplace.visualstudio.com/items?itemName=vstirbu.vscode-mermaid-preview

docs: fix and enhance mermaid diagrams

---

functions/src/definitions/common/parameters/userResponses.json
functions/src/definitions/common/responseUtils.ts

Resolves #209
Resolves #210 
Minor changes to copy only, as well as bugfixes

fixed copy errors

---

functions/src/definitions/common/parameters/userResponses.json
functions/src/definitions/common/responseUtils.ts

- Resolves #228 
- Added new message for matched, human-categorised message

updated matching

---

functions/src/definitions/api/handlers/getChecker.ts

Firebase doesnt allow queries with double inequalities in actual enviroment, although it works for local emulator
Did client side filtering for one of the query conditions (category != null)

Remove double inequality query

---

functions/src/definitions/eventHandlers/onVoteRequestUpdate.ts

- Resolves #268 
- Simple fix to check for whatsapp instead of checking for not agent

stop attempting to send wa messages to tg users

---

functions/src/definitions/eventHandlers/userHandlers.ts

#269 
- made the referral check less tight, so it can accomodate meta checks as well
- now check is hardcoded/delinked from the user_responses variable. but the hardcoded stuff is unlikely to change.

Cater for Meta CTA

---

functions/src/definitions/api/handlers/getChecker.ts
functions/src/definitions/batchJobs/batchJobs.ts
functions/src/definitions/common/mediaUtils.ts
functions/src/utils/time.ts

Similar to AppENV. Utilise enums to dictate the commonly used time in milliseconds for intellisense and shared understanding of time used in the project.

Refactor: Utilising enums

---

checkers-app/package.json

added tsc to uat build

---

functions/src/definitions/api/handlers/patchChecker.ts

prevent API from updating isAdmin or tier

---

checkers-app/src/components/common/BackButton.tsx
checkers-app/src/components/common/Header.tsx
checkers-app/src/components/common/Layout.tsx
checkers-app/src/components/vote/index.tsx

Floating back button was ugly. added back button to header.
It'll go back to /votes if on the actual voting page.
Otherwise just go back as it would on browser.

Moved back button to header

---

checkers-app/src/components/common/Header.tsx
checkers-app/src/components/dashboard/CelebrationDialog.tsx
checkers-app/src/components/dashboard/index.tsx

- Added padding to header
- Made page title smaller
- Changed celebration splash screen text

added padding to header

---

functions/src/definitions/webhookHandlers/handler.ts

Added try catch to whatsapp handler

try catch whatsapp handler

---

checkers-app/src/components/common/Layout.tsx
functions/src/definitions/eventHandlers/onCheckerUpdate.ts

3.0.5-hotfix

---

README.md
firebase.json
functions/src/definitions/webhookHandlers/specialCommands.ts

- New devs on Mac can't use localhost 5000 cos it's taken up by airplay

change hosting to localhost:5002

---

functions/src/definitions/eventHandlers/onVoteRequestUpdate.ts

- Resolves #339
- Added logic to check if voteRequest was created before the turn of the month. If so, to ignore for leaderboard

disregard votes from before month

---

functions/src/definitions/eventHandlers/onInstanceCreate.ts

- #359 
- Check whether voteRequest is created for this factchecker already, during dispatchPoll
- Set isPollStarted to true before dipatchPoll rather than after

fixed multiple vote requests for a message

---

functions/src/definitions/batchJobs/batchJobs.ts
functions/src/definitions/common/sendTelegramMessage.ts

- Make it easier for people to deactivate when they receive the reminder message

Added reply keyboard markup

---

functions/src/definitions/eventHandlers/userHandlers.ts

- Default utmSource of none not informative enough. Decided to change to "direct" for those who add the number directly or otherwise do not send in prepopulated link

changed default utmSource

---

checkers-app/src/pages/Onboarding.tsx

- In #379 we tried to change target to "_blank" but it only works on desktop, not mobile phones
Use window.Telegram.WebApp.openLink instead

updated links

---

functions/src/definitions/common/responseUtils.ts

changed getResponsesObj to getUserResponsesObject

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

- New secrets were missing from the onCheckerPublishTelegram
- Gave onCheckerPublishTelegram access to new secrets

added missing secrets

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

- SURE LC logo not sending, when using Telegram fileID in a different chat
- Changed to using public URL
- Also added awaits and logs

fixed image sending

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

- Copy could be improved for onboarding
- Improved copy!

improved copy

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

- Some minor textual issues
- fixed accordingly

textual issues

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

- Resolves #405
- Disable link preview for quiz message

removed link preview from quiz msgs

---

checkers-app/src/components/myvotes/MessagesDisplay.tsx

- Pending/Voted headers with white background in dark mode
- Fixed

Fixed UI bug

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

New checkers dont know where they will receive the messages and where to do the voting.
Be clearer in final steps of onboarding when they will receive messages and where they will vote

added message at the end of onboarding

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts
functions/src/definitions/webhookHandlers/handler.ts
functions/src/definitions/webhookHandlers/handlers/adminHandlerTelegram.ts

- Resolves #412 
- Added new webhook path for telegram admin bot webhook
- Added automation of welcome message when new ppl join

Automate welcome message 

---

checkers-app/src/components/dashboard/ProgressCard.tsx
checkers-app/src/components/dashboard/index.tsx
checkers-app/src/services/api.ts
functions/src/definitions/api/handlers/patchChecker.ts
functions/src/definitions/api/interfaces.ts

- Resolves #418
- Implemented ideas in the issue
- Added ability to withdraw from program

checker UX improvements

---

checkers-app/src/components/dashboard/index.tsx

- Small textual issues
- Fixes

fixed textual issues

---

checkers-app/src/components/dashboard/index.tsx

- Request to change wording for branding

Refactor dashboard text for CheckMate Checker's Program

---

functions/src/definitions/common/genAI.ts
functions/tsconfig.json

- Resolves #425
- Changed regex replacement to replaceall

changed to replaceall

---

checkers-app/src/components/vote/NvcOptions.tsx

- NVC wording still using info wordings for the L2 voting
- Updated

updated wordings

---

checkers-app/src/components/vote/VotingChart.tsx

- Charts very cramped
- shorterned wordings

made charts less cramped

---

checkers-app/src/components/vote/VoteCategories.tsx

- Unsure wording slightly vague
- Improved wording

amended unsure wording

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

- wa.me link instead of ref.checkmate link in prod for checkers onboarding (WA step)
- Typo in code

fixed typo

---

functions/src/definitions/api/handlers/getCheckerVotes.ts
functions/src/definitions/api/handlers/postVoteRequest.ts
functions/src/definitions/batchJobs/batchJobs.ts
functions/src/definitions/common/cloudTasks.ts
functions/src/definitions/eventHandlers/onInstanceCreate.ts
functions/src/definitions/eventHandlers/onVoteRequestCreate.ts
functions/src/definitions/taskHandlers/autoPass.ts
functions/src/index.ts
functions/src/types.ts

- Resolves #444
- Added cloud tasks queue
- Queue a cloud task to check if category is null after 48 hrs and if so set to pass.

added cloud tasks to auto-pass after 48 hrs

---

.github/workflows/run-tests.yml
Dockerfile
checkers-app/package-lock.json
checkers-app/package.json
checkers-app/src/components/vote/VoteCategories.tsx
checkers-app/src/components/vote/VoteResult.tsx
checkers-app/src/components/vote/VoteTags.tsx
checkers-app/src/components/vote/VotingChart.tsx
checkers-app/src/components/vote/index.tsx
firebase.json
functions/package-lock.json
functions/package.json
functions/src/definitions/common/cloudTasks.ts
functions/src/definitions/common/parameters/userResponses.json
functions/src/definitions/common/responseUtils.ts
functions/src/definitions/common/statistics.test.ts
functions/src/definitions/common/statistics.ts
integration-tests/checkmate.postman_collection.json
integration-tests/env.json
package-lock.json
package.json

- Created an accordion on the voting page to allow users to select the “generated” tags. 
- If “generated” tag is selected and users submit the form with the category, {generated: true} would be stored in the Database.
- If {generated: true} stored in the tag in the DB, then “This is a generated information” message will be concatenated at the end of the usual message. Not very sure what should be the message, hence just putting a random message for now.

336 add tag for generated image

---

checkers-app/src/components/vote/InfoOptions.tsx
checkers-app/src/components/vote/MessageCard.tsx

- Resolves #451
- Moved caption above image

shift caption above image

---

checkers-app/src/components/vote/NvcOptions.tsx

- Notion of "Credible" confusing in the context of banal messages
- Rephrased the way the question is phrased

updated text

---

checkers-app/src/components/vote/VoteTags.tsx
checkers-app/src/components/vote/index.tsx

- Keyboard blocking the tag selection
- Tag labels not seeable in dark mode
- Set isSearchable={false} in the Select Component for the Tags to disable search functionality so that the keyboard would not be shown on mobile device. 
- Set auto scroll down to allow the dropdown selections to be better shown on mobile device, previously the selection was only shown partially.

Minor UI Changes for Tag Selection

---

functions/src/definitions/common/responseUtils.ts
functions/src/definitions/eventHandlers/userGenericMessageHandlers.ts
functions/src/definitions/webhookHandlers/handler.ts
functions/src/services/common/userManagement.ts
functions/src/services/whatsapp/referrals.ts

- #390 but whatsapp welcome messages are down as per https://developers.facebook.com/support/bugs/535812315510049/?join_id=fc4518869aeeed328
- Set up the handling and new referral mechanism (time-based) first, but didn't actually implement anything yet

added conversational component handling

---

functions/src/definitions/common/counters.ts

- Resolves #459 
- included irrelevant (aka trivial) into the harmless count

added in irrelevant count to harmless

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts
functions/src/definitions/webhookHandlers/handlers/adminHandlerTelegram.ts

- To move some of the wordings from the initial joining message and into the pinned message instead
- As above

improved wordings

---

checkers-app/src/components/common/Menu.tsx

- Typescript thing not compiling
- Removed react import

removed react import

---

functions/src/definitions/api/handlers/postChecker.ts
functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts
functions/src/definitions/eventHandlers/checkerHandlerWhatsapp.ts
functions/src/definitions/webhookHandlers/specialCommands.ts

Certificate url initialised as "" and not null
Previously cert url was initialised as "" and not null, which is non-standard 
1. Fixed this
---

changed cert url to null

---

.github/pull_request_template.md
.github/pull_request_template.yml
.github/pull_request_template/deploy_to_prod.md
.github/pull_request_template/deploy_to_uat.md

github PR template stuff

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts

Not providing checkers good resources.
Added facticity, virustotal, and scamshield app as resources
Added facticity, virustotal, and scamshield app as resources when typing / resources
---

added more resoruces

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts
functions/src/definitions/webhookHandlers/handlers/adminHandlerTelegram.ts

Not sure why merging with main added more weird stuff but fixed that
Removed extra bits
---

removed extra stuff

---

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts
functions/src/definitions/webhookHandlers/handlers/adminHandlerTelegram.ts

Unsure why merge from main overrode stuff
**Example:**
Amended back to the Checkers chat ID
Amended back to the Checkers chat ID

Fixed issues

---

functions/src/definitions/common/responseUtils.ts
functions/src/definitions/eventHandlers/userNavigationHandlers.ts
functions/src/types.ts

Resolves #488 
Pass language directly to the sendMenuMessage function, rather than pass the userSnap without re-calling it.
1. Make a new optional argument to sendMenuMessage
2. Set default to null
3. If null, use language from userSnap, otherwise use argument to send

updated menu message

---

checkers-app/src/components/dashboard/CelebrationDialog.tsx
functions/src/definitions/api/handlers/patchChecker.ts
functions/src/definitions/eventHandlers/onCheckerUpdate.ts

- Resolves #490 
Backend: Check programEnd is set before allowing API to set isOnProgram to false
Frontend: Only complete program when CelebrationDialog is Open
As per description
---

Fixed isOnProgram bug

---

checkers-app/src/components/vote/InfoOptions.tsx

Typescript compilation bug
Removed unnecessary alert import
As above
---

removed alert

---

functions/src/definitions/batchJobs/batchJobs.ts

Shift batch job timing deactivation and completion check are not both at 8:11pm.
1. Changed check completion to 8:41 pm
1. Changed check completion to 8:41 pm
---

updated batch job timing

---

functions/.env.local.test
functions/src/definitions/eventHandlers/onMessageCreate.ts
functions/src/definitions/eventHandlers/onMessageUpdate.ts
functions/src/definitions/eventHandlers/userGenericMessageHandlers.ts
functions/src/index.ts
functions/src/types.ts

feature: admin notification telegram chat

---

functions/src/definitions/batchJobs/batchJobs.ts
functions/src/definitions/common/responseUtils.ts
functions/src/services/user/userManagement.ts
functions/src/types.ts

- variable name poorly named, submission limit is now daily not monthly
**Example:**
- Made name generic
1. Nothing much, just simple changes to var names and types
---

renamed monthly submission limit to generic

---

functions/src/definitions/common/responseUtils.ts

Disable draft mode for WhatsApp flows
As described
---

edited to trigger published flow

---

firebase.json
functions/package-lock.json
functions/package.json
package-lock.json

- Node 18 soon to be deprecated
- Changed function runtime to node 22.
---

updated to node 22

---

functions/src/definitions/eventHandlers/userNavigationHandlers.ts

fixed issue with waitlist flow response

---

functions/src/definitions/common/parameters/thresholds.json

Updated free tier quota to 10
---

update free tier to 10

---

functions/src/definitions/common/parameters/thresholds.json

Tests failing after thresholds free tier changed to 10
**Example:**
Changed back to 5
As described
---

change back to 5

---

checkers-app/src/components/myvotes/CommunityNoteCard.tsx
checkers-app/src/components/vote/CommunityNoteCategories.tsx
checkers-app/src/components/vote/DoneButton.tsx
checkers-app/src/components/vote/VoteCategories.tsx
checkers-app/src/components/vote/VotingSystem.tsx
checkers-app/src/components/vote/index.tsx
checkers-app/src/services/api.ts
functions/package-lock.json
functions/package.json
functions/src/definitions/api/handlers/getMessage.ts
functions/src/definitions/api/handlers/getVote.ts
functions/src/definitions/api/handlers/patchVoteRequest.ts
functions/src/definitions/api/handlers/postVoteRequest.ts
functions/src/definitions/api/interfaces.ts
functions/src/definitions/eventHandlers/onVoteRequestUpdate.ts
functions/src/services/checker/votingService.ts
functions/src/types.ts

**Example:**
- Resolves #542
- Resolves #543 
Add commentOnNote text field, to allow checkers to provide an optional explanation if they want to provide an explanation to the LLM evaluation. 
1. Add a text field 
2. Add commentOnNote field database
---

Add commentOnNote Text field

---

functions/src/definitions/common/responseUtils.ts

Resolves #562
Wrapped custom note reply and community note reply inside if-else
---

Fixed bug with both custom reply and community note sending

---

functions/src/definitions/common/responseUtils.ts

**Example:**
Resolves #569 
Added replace for community note. Simple change
---

fixed get_more_cta

---

functions/src/definitions/common/parameters/userResponses.json

Wording changes
Updated wordings
---

change to "Get More"

---

checkers-app/src/components/vote/VotingSystem.tsx
functions/src/definitions/webhookHandlers/specialCommands.ts

**Example:**
Resolves #565
UI changes to check if voteCategory = pass and give submit button there and then.
As above
---

if pass, dont have to vote on comm note

---

functions/src/definitions/eventHandlers/updateTypesense.ts

Resolves #575 
Syncs downvoted data as well as AI response data to typesense. If custom reply is in place, use that instead.
As described
---

synced AI responses to typesense

---

functions/src/definitions/eventHandlers/updateTypesense.ts

Typesense should have access to sources as well
**Example:**
Synced community note sources to typesense
As above
---

added sources

---

functions/src/definitions/batchJobs/batchJobs.ts

New checkmate website requires some statistics.
Sync stats to public bucket every 5 mins
As above
---

sync stats

---

functions/src/definitions/common/machineLearningServer/operations.ts
functions/src/definitions/eventHandlers/userGenericMessageHandlers.ts

send all to cloudflare

---

functions/src/definitions/common/machineLearningServer/operations.ts
functions/src/definitions/eventHandlers/userPreOnboardingHandler.ts

User preonboarding handler no access to cloudflare API key
Added access
as above
---

added secret to userPreOnboardingHandler

---

functions/src/definitions/eventHandlers/userGenericMessageHandlers.ts

- People who are yet to onboard shld have their status set to false if they are existing users and send in stuff (if not already)
**Example:**
Checks if isOnboardingComplete === null, if so set it to false
---

set those who send in prepopulated to isonboardingcomplete = false

---

.github/workflows/firebase-deploy.yml

Node version not on par in GH actions
Updated node version
As above
---

update node version in GH actions

---

functions/src/definitions/common/parameters/userResponses.json
functions/src/definitions/common/responseUtils.ts

Extra unnecessary step in onboarding from the "Show me how to use CheckMate flow"
Removed this step
As above 
---

updated onboarding flow from demo message

---

functions/src/definitions/webhookHandlers/handlers/adminHandlerTelegram.ts

- Old code to welcome checkers is executing when it shouldn't.
Removed the on new chat member handler for the admin bot handler.
as above
---

removed message for new checkers

---

functions/src/definitions/webhookHandlers/handlers/adminHandlerTelegram.ts

No unpublish button if people fat finger.
Added unpublish button to admin bot
As above
---

feat: add unpublish button to admin bot

---

functions/src/definitions/common/parameters/userResponses.json
functions/src/definitions/common/responseUtils.ts
functions/src/definitions/eventHandlers/userNavigationHandlers.ts

"I see how it works" button doesn't work in postonboarding although it is sent by the template
Created a handler for it
As above 
---

added try or share cta

---

functions/src/definitions/common/responseUtils.ts
functions/src/services/user/userManagement.ts
functions/src/types.ts

- Resolves #617 
Added new hasExperiencedBespokeCheck field
- Added new field to user data
- Updates upon preOnboarding sample check message or if user receives a communityNote or customReply
---

added hasExperiencedBespokeCheck to user data

---

functions/package-lock.json
functions/package.json
package-lock.json

Fixed bug with normalize-url
Updated normalize-url version to 8
As above
---

updated normalize-url

---

checkers-app/src/components/vote/VoteOption.tsx

Percentages in community note vote graphic in vote results chart not truncated to 2 DP
Fixed
Fixed
---

fixed percentage to 2 decimal places

---

functions/src/definitions/webhookHandlers/specialCommands.ts

People typing //mockdb into UAT regularly broke stuff, e.g. the onboarding video ID
Removed //mockdb from UAT
As above
---

removed //mockdb in uat

---

functions/src/services/checker/votingService.ts

- Resolves #627 
Removed the part in the code that added the isTesterCheck to the query when getting the eligible checkers
---

Trigger all checks all the time
