README.md, functions/package.json, functions/tsconfig.json
This method works pretty well as tsc caches the previously built files and rebuilds files changed only instead of rebuilding the whole project.
Requires running 2 shell windows, one monitors for tsc errors, while the other is used for the emulator logs.
=> Setup typescript hotreload for local emulator usage

functions/src/definitions/common/sendWhatsappMessage.js
Hotfix for issue where whatsapp messages that reply to earlier messages are throwing API errors
https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages#replies
https://business.facebook.com/direct-support/question/2257768874410757/?force_full_site=0&business_id=1785741798462872
=> disable reply messages

functions/src/definitions/common/sendFactCheckerMessages.js
Bug description:
On cases where L2 categorisation/voting was already sent (whatsapp returned 200) previously, but checker did not complete it (could be checker stopped halfway and forgot, or WABA API returned 200 but did not actually send), checkers may eventually re-request the L1 categorisation message (perhaps the reminder message triggers them to). In such cases, because the triggerL2Vote or triggerL2Others variables are already true, they will not receive the L2 vote.
Fix:
Reset the 2 variables to null on the sending of the L1 Categorisation Message
=> update trigger variables to null on 1st level sent

functions/src/definitions/checkerHandlers.js, functions/src/definitions/common/sendFactCheckerMessages.js
Changes:
- Shifted the reset of triggerL2Others and triggerL2Vote up 1 level, from sendL1CategorisationMessage to onFactCheckerYes. Otherwise, it doesn't reset the 2 variables when the message goes through the "info" autocategorisation flow, leading to rare situations where checkers who re-requested the L2VoteMessage to be sent not receiving anything.
=> Shifted L2VoteSent and L2OthersSent one lvl up

documentation/dataSchema.md, functions/src/definitions/checkerHandlers.js
Summary:
- Although storageUrl was deleted from messages, getSignedUrl in the onFactCheckerYes logic was still reading from it.
Fix:
- Read storageUrl from latestInstance instead. Other erroneous fields fixed too.
=> [Bug] getSignedUrl reading deleted field from messages

functions/src/definitions/userHandlers.js
Resolves #134 
Summary:
- Made sure machineCategory is checked before calling .split on it
=> [Bugfix] Error in imageMessageHandler when machineCategory is undefined

.gitignore, package.json
Sanity check to check functionality:
- Open the firebase emulator firestore tab
- Create new entries
- Ctrl + C, close connection with emulator
- Check that new folder `local-data` in project root has been created
- Start the emulator
- Verify that the data is present
This commit is intended to improve the DX, and remove the constant need to invoke `/mockdb` to populate the emulator with dummy data
=> feat: add persistence to firebase emulator

functions/package.json, functions/src/definitions/common/utils.test.ts, functions/src/definitions/common/utils.ts
Added unit test for `stripPhone` utility function.
While working on unit tests I discovered a test case that wasn't working as documented in Issue #230.
Before refactoring the function, I performed some validations to make sure the `findPhoneNumbersInText` function was working as intended. 
```js
import { findPhoneNumbersInText } from "libphonenumber-js"
const str =
"https://youtu.be/oglCjESHJ70?si=JznEryFFXUZ6y2ma ~Dayan +6583294024 Who are you ~SLTan米+6583294023 你是红桂桥Ada？ ~Dayan +6583294023 No"
console.log(findPhoneNumbersInText(str))
console.log(
`56: ${str.charAt(56)}; 67: ${str.charAt(67)}; Slice: ${str.slice(56, 67)}`
)
console.log(
`87: ${str.charAt(87)}; 98: ${str.charAt(98)}; Slice: ${str.slice(87, 98)}`
)
console.log(
`116: ${str.charAt(116)}; 127: ${str.charAt(127)}; Slice: …
```
=> stripPhone fix and unit test

checkers-app/src/components/vote/VoteCategories.tsx
- Resolves #280 
- Backend patchVotesRequest handler returns 400 under the following circumstance
``` 
if (category !== "info" && truthScore != null) {
return res
.status(400)
.send("Truthscore can only be submitted for info category")
}
```
- But frontend currently doesn't clear truth score or set it to null if a non-info category is submitted.
- Make frontend submit null truth score if non-info category is submitted
=> send truth score of null when category is not info

functions/src/definitions/eventHandlers/onVoteRequestUpdate.ts
Previously telegram reply markup was not updating properly.
Basically voteRequestUpdate didnt have access to the secret.
=> Add secret name to voteRequestUpdate

checkers-app/src/components/common/Layout.tsx
NavBar was hiding the submit button and other functionality
By adding back the padding to the children container, we avoid this problem
=> added back padding-bottom

functions/src/definitions/eventHandlers/onCheckerUpdate.ts
Bugfix as ai type checker data object does not contain programData, which is causing errors on this line !postChangeData.programData.isOnProgram
=> do not execute if it's ai type

checkers-app/src/pages/Onboarding.tsx
- When onboarding, checkers who click on links (e.g. privacy policy or quiz) will open them in the Telegram webapp. Thereafter, they cannot navigate back to the onboarding page to continue as telegram webapp has no back gesture built in, or a back button.
- Made all anchor tags have target="_blank"
=> open onboarding links in new window

functions/src/definitions/batchJobs/batchJobs.ts, functions/src/definitions/eventHandlers/onVoteRequestUpdate.ts
- Resolves #382 
- Deactivates checkers who have not voted on anything in the past 72 hours.
- Make it so that if checkers vote, they are reactivated
=> deactivate inactive checkers

functions/src/definitions/common/otp.ts, functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts
- Old whatsapp checkers do not have their stats preserved when migrating
- Old votes will be tied to checkers who do not exist
- Have some logic to continue using the old whatsapp checkers data, and delete the new one (as opposed to vice versa)
=> migrate old whatsapp checkers to the new bot

functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts
- Bug where checker sends telegram message to the bot without first typing /onboard.
- Checker onboarding message in checkers group still refers to the old term "CheckMate's"
- Check for empty query
=> check for empty querySnap

functions/src/definitions/webhookHandlers/handlers/adminHandlerTelegram.ts
- Welcome message still refers to "CheckMates" and not "checkers"
- Fixed
=> edited welcome message

checkers-app/src/components/vote/VoteTags.tsx
- Tag called "incorrect" not informative
- Changed to incorrect usage
=> renamed to incorrect usage

checkers-app/src/components/vote/InfoOptions.tsx
- Now that info options depends on numberPointScale value returned in API, it should handle cases where this missing
- Fixed
=> handle missing numberpoint scale

Dockerfile
- https://github.com/firebase/firebase-tools/releases/tag/v13.22.0 seems to have broken the firebase emulator. Now its complaining unable to authenticate checkmate-uat
Error: Failed to get Firebase project checkmate-uat. Please make sure the project exists and your account has permission to access it.
- Rolled back to v13.20
=> rolled back firebase tools

checkers-app/src/components/dashboard/CelebrationDialog.tsx
Previously, on completion of the practitioner program, checkers could opt out of the program, which wasn't a good outcome.
Removed the button to opt out at the end, or to opt in. Basically, the default is now opt in. To opt-out, we add a liner to explain that they can /deactivate in the bot.
1. Removed buttons to opt out/opt in
2. Added close dialog button instead
3. Changed wordings of prompt
---
=> removed forced choice to continue / leave

functions/src/definitions/common/responseUtils.ts
Erroneous response for unsure messages
Previously was passing in "UNSURE" instead of responses["UNSURE"]
Fixed error
---
=> fixed unsure response

functions/src/definitions/common/responseUtils.ts
- #486 
- Fixed a simple code mistake that lead to unsure response being "UNSURE" rather than responses["UNSURE"]
=> 3.3.5-hotfix

functions/src/definitions/common/counters.ts, functions/src/definitions/common/parameters/thresholds.json, functions/src/definitions/eventHandlers/onVoteRequestUpdate.ts
**Example:**
Resolves #493 
1. Removed nvc-can't tell count from adding to harmless count
2. Making both NVC's count as 1 category, then using which between credible and can't tell the majority to determine the response to user, similar to how it's done for scam and illicit.
As above
---
=> irrelevant no longer harmless and changed nvc

checkers-app/src/components/common/ReactivationModal.tsx, checkers-app/src/components/dashboard/index.tsx, checkers-app/src/components/leaderboard/table.tsx, checkers-app/src/components/vote/InfoOptions.tsx, checkers-app/src/types.d.ts, functions/src/types.ts
- Resolves #500
Frontend changes to check checkerActivity status before letting them access the leaderboard API. Also did the same for the dashboard page.
1. Created new checker data item isAgainstReactiviating in frontend to track if the checker cancelled the reactivation request
2. Created new dialog modal for reactivating the checker
3. Check for isActive before showing popup modal in leaderboard page
4. Check for isActive and isAgainstReactivating before showing popup modal in dashboard page.
5. Also removed old alert informing checkers that scale had shifted from 1-5 to 0-5
---
=> handle inactive upon reaching leaderboard/dashboard

functions/src/definitions/api/handlers/postChecker.ts, functions/src/definitions/batchJobs/batchJobs.ts, functions/src/definitions/eventHandlers/checkerHandlerTelegram.ts, functions/src/definitions/eventHandlers/checkerHandlerWhatsapp.ts, functions/src/definitions/taskHandlers/firstCompletionCheck.ts, functions/src/definitions/taskHandlers/secondCompletionCheck.ts, functions/src/definitions/webhookHandlers/specialCommands.ts, functions/src/index.ts, functions/src/services/checker/managementService.ts, functions/src/services/checker/nudgeService.ts, functions/src/types.ts, functions/src/utils/time.ts
- Resolves #510
Cloud tasks doesn't support scheduling tasks more than 30 days into the future. Since we require the completion checks to be after 60 and 90 days, we have to implement it a different way. As a result, this was switched to being based on batch-job.
1. Removed cloud task creation and removed cloud task functions for 1st and 2nd completion checks
2. Added new daily batch job to perform the 1st and 2nd completion check
3. Reduced inactivity reminders from 4 to 2 (14, and 28 days) to keep within 30 day limits 
---
=> shifted completion checks to batchjob

checkers-app/src/components/vote/MessageCard.tsx, checkers-app/src/components/vote/index.tsx
**Example:**
1. move that sender thing into the message
2. have a header for the message section and make sure it looks okay when there's a caption. Message section should have caption, image and sender for image message, and text and sender for text message
3. align the community note header with the message section header
1. Frontend changes in file checkers-app/src/components/vote/MessageCard.tsx
---
=> UI Changes to Voting Page

functions/src/definitions/eventHandlers/updateTypesense.ts
Typesense database cannot filter for absense of response field.
**Example:**
Added a hasResponse field to Typesense
As described
---
=> sync hasResponse field to typesense

functions/src/definitions/common/responseUtils.ts
Resolves #634 
Additional const keyword means global variable not set properly
>   The fix: The responseText defined inside the "unsure" case block (lines 1475-1488) needs to be assigned to the outer responseText variable declared at line 1258.
> 
>   Change line 1475 from:
>   const responseText = getFinalResponseText({
>   to:
>   responseText = getFinalResponseText({
> 
>   This ensures the outer responseText variable is set before the break statement, making it available for the database update at line 1543.
> 
> > check now. have i fixed the issue?
> 
> ⏺ Yes, you've fixed the issue!
> 
>   By changing line 1475 from const responseText to just responseText, you're now correctly assigning to the outer responseText variable that was declared at line 1258.
> 
>   This means when the …
=> fix: fix instance not updated properly when category unsure
